services:
  db:
    image: postgres:16
    container_name: qwertix-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qwertix
      PGPORT: 54321
    volumes:
      - qwertix_db_data:/var/lib/postgresql/data
    ports:
      - "54321:54321"

  adminer:
    image: adminer
    container_name: qwertix-adminer-dev
    restart: always
    ports:
      - 8081:8080

volumes:
  qwertix_db_data:
